# Travis-CI
dist: bionic
language: python
os: linux

matrix:
  include:
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'
    # Docker dev image
    - sudo: true
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m unittest discover
  - behave
  - coverage erase
  - coverage run test_webapp.py && coverage html
  - pylint --output-format=text scripts/vault_keeper.py

after_success:
  - codecov
