dist: bionic
language: python

matrix:
  include:
    - python: '3.6.10'
    - python: '3.7.6'
    - python: '3.8'
    # Docker dev image
    - sudo: required
      services:
        - docker

      before_install:
        - pip3 install -r requirements.txt
      install: []

      script:
        - docker build --tag "$IMAGE_NAME" .
        
